##
#
# 
#  _____                 _            _             
# |_   _|               | |          | |            
#   | |  _ __ ___  _ __ | | __ _  ___| |_ ___  _ __ 
#   | | | '_ ` _ \| '_ \| |/ _` |/ __| __/ _ \| '__|
#  _| |_| | | | | | |_) | | (_| | (__| || (_) | |   
# |_____|_| |_| |_| .__/|_|\__,_|\___|\__\___/|_|   
#                 | |                               
#                 |_|         
#
#
# Implactor (c) 2018
# Everything needs on (plugin.yml)
# ------===------
# > Author: Zadezter
# > Team: ImpladeDeveloped
# 
#
##

---

name: Implactor
version: IR-2.0_BETA
api:
- 3.0.0
- 3.2.0
- 4.0.0
main: Implactor\Implade
description: A classic plugin, more added authorized features to here!
author:
- Zadezter
- FreeGamingHere
website: https://github.com/ImpladeDeveloped

commands:
    bot:
       description: Spawn the bot human at your coordinates! (FormAPI required)
       permission: implactor.bot
    icast:
       description: Broadcast your message to all online players!
       permission: implactor.broadcast
    vision:
       description: Open a vision menu UI! (FormAPI required)
       permission: implactor.vision
    visible:
       description: Open the player visible menu UI! (FormAPI required)
       permission: implactor.visible
    wild:
       description: Teleport to random spot of wilderness!
       permission: implactor.wild
    ping:
       description: Ping your connection in-game server!
       permission: implactor.ping
    gms:
       description: Change the gamemode to Survival!
       permission: implactor.gamemode
    gmc:
       description: Change the gamemode to Creative!
       permission: implactor.gamemode
    gma:
       description: Change the gamemode to Adventure!
       permission: implactor.gamemode
    gmsc:
       description: Change the gamemode to Spectator!
       permission: implactor.gamemode
    soccer:
       description: Spawn the soccer ball at your coordinates!
       permission: implactor.soccer
    clearinv:
       description: Clear all items from inventory!
       permission: implactor.inventory
    cleararmor:
       description: Clear armours from own characters!
       permission: implactor.inventory
    iabout:
       description: Take a look about Implactor plugin!
       permission: implactor.about
    rainbow:
       description: Open the rainbow armor menu UI! (FormAPI required)
       permission: implactor.rainbow
    head:
       description: Sell player's heads with command!
       permission: implactor.head
         
permissions:
    implactor.*:
     description: "Allow operators get access to all Implactor commands"
     default: op
    implactor.wild:
     description: "Allow players to random teleporting to wilderness"
     default: true
    implactor.head:
     description: "Allow players to sell heads with command"
     default: true
    implactor.ping:
     description: "Allow players to ping their connection in-game server"
     default: true
    implactor.visible:
     description: "Allow players to open the player visibility menu UI"
     default: true
    implactor.bot:
     description: "Allow operators to spawn their own bot human"
     default: op
    implactor.broadcast:
     description: "Allow operators to broadcast their messages to all online players"
     default: op
    implactor.about:
     description: "Allow players to see about Implactor plugin"
     default: true
    implactor.vision:
     description: "Allow operators to open the vision menu UI"
     default: op
    implactor.gamemode:
     description: "Allow operators to change their gamemodes in-game server"
     default: op
    implactor.soccer:
     description: "Allow operators to spawn their soccer ball"
     default: op
    implactor.inventory:
     description: "Allow operators to clear their items from inventory and armors"
     default: op
    implactor.rainbow:
     description: "Allow operators to open the rainbow armor menu UI"
     default: op
##     
# Not related to command permissions
##
    implactor.anti:
     description: "Allow to prevent players from spamming/swearing/advertising in chat messages"

...
