# ××××× = ××××× = ×××××
# Implactor Configuration
# Made by Zadezter
# > -----
# Discord: Zadezter#0207
# Twitter: @Zadezter
# ××××× = ××××× = ×××××
---

# This is config version on Implactor plugin.
# Do not change the version or it will make a config broken.
Version: 3

# Select a language you'd like to choose for plugin.
# ××××× ----- ××××× ----- ×××××
# Available Languages:
# - English
# - Russian
# ××××× ----- ××××× ----- ×××××
# Useful and good for this plugin.
language: 'English'

# Enable/Disable the update checker for Implactor.
update-checker: true

# Set a timer to clear lagg automatically.
# Default = 480 seconds.
clear-timer: 480

# Set amount of how much killer get money after slained one player.
# "220" in-game money is recommend.
killer-money: 220

# Set amount of player head money to sell.
# "100" in-game money is recommend.
# NOTE: Don't set to higher, it makes some players will be rich!
item-head-sell-money: 100

# Enable/Disable some particles on every features.
bot-particles: true
spawn-particles: true
death-particles: true

# Enable/Disable the lightning for Join & Quit events.
lightning-events: true

...
