##
#
# 
#  _____                 _            _             
# |_   _|               | |          | |            
#   | |  _ __ ___  _ __ | | __ _  ___| |_ ___  _ __ 
#   | | | '_ ` _ \| '_ \| |/ _` |/ __| __/ _ \| '__|
#  _| |_| | | | | | |_) | | (_| | (__| || (_) | |   
# |_____|_| |_| |_| .__/|_|\__,_|\___|\__\___/|_|   
#                 | |                               
#                 |_|         
#
#
# Implactor (c) 2018
# The place for configuration file.
# It's designed here by Zadezter.
# ------===------
# > Author: Zadezter
# > Team: ImpladeDeveloped
# 
#
##

---

# Select the language for Implactor plugin such a messages.
# List Available:
# ( English | Russian )
language: "English"

# The important of configuration version on Implactor plugin.
# [WARNING]: Do not CHANGE the configuration version!
Version: 5

# Auto-update checker, to detect the new version of Implactor plugin.
# You can enable or disable the feature.
update-checker: true

# Set a timer of interval seconds for Automatic Clear Lagg feature.
# Make sure the number of seconds it's correctly.
# You can disable by set it false or put a invalid numbers, but it shows a warning message on console.
clear-timer: 480

# Shows a welcome and leave messages on chat screen.
# You can enable or disable the feature.
welcomer-message: true

# Shows a plugin notice message on chat screen.
# [NOTE]: It'll show a notice message that you were using Implactor plugin.
# You can enable or disable the feature.
notice-message: true

# That are some of particle features on Implactor plugin.
# To prevent from lagg, we recommend you to disable, that's your choice.
spawn-particles: true
death-particles: true
bot-particle: true

# Death Human / Corpse will spawned on your coordinates after you death.
# [NOTE]: If you too far away from the corpses or teleport to another world, the corpses will standing up and no way to despawn it.
# You can enable or disable the feature. (To clear all and prevent the corpses from standing up.)
death-human: true

# Animations & Sounds from PMMP packet will played to other players.
# You can enable or disable the feature.
guardian-join: true
totem-respawn: true

# Lightning strike will appear when someone join and left the server.
# You can enable or disable the feature.
lightning-events: true

# Set amount of money to killer when slained one oppoment per player.
# [NOTE]: Don't set to the higher amount of money, they'll be get riches!
killer-money: 150

# Set amount of money for selling one per head via using commands.
# [NOTE]: Don't set to the higher amount of money, they'll be get riches!
item-head-sell-money: 100

# Make you get bleeding once the player hits you.
# You can enable or disable the feature.
blood-hit-players: true

...
